site_name: Spotify
site_url: https://requisitos-de-software.github.io/2022.2-Spotify
repo_url: https://github.com/Requisitos-de-Software/2022.2-Spotify
repo_name: 2022.2-Spotify
edit_uri: ""
copyright: UnB - Faculdade do Gama &copy; 2022
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - link: https://github.com/Requisitos-de-Software/2022.2-Spotify
      icon: fontawesome/brands/github

    - link: https://www.spotify.com
      icon: fontawesome/brands/spotify

theme:
  name: material
  logo: img/social.png

  features:
    - navigation.tabs

  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
